<?php

/**
 * @file plugins/importexport/fullJournalTransfer/filter/import/NativeXmlExtendedArticleFilter.php
 *
 * Copyright (c) 2014-2024 Lepidus Tecnologia
 * Copyright (c) 2025-2026 academic-journals-cz
 * Distributed under the GNU GPL v3. For full terms see the file docs/COPYING.
 *
 * @class NativeXmlExtendedArticleFilter
 *
 * @brief Imports a submission together with its editorial workflow: stage
 *  assignments, review rounds, review assignments, decisions, discussions and
 *  the activity log.
 */

namespace APP\plugins\importexport\fullJournalTransfer\filter\import;

use APP\core\Application;
use APP\facades\Repo;
use APP\plugins\importexport\fullJournalTransfer\classes\ActivityLog;
use APP\plugins\importexport\fullJournalTransfer\classes\FullJournalFilterTrait;
use APP\plugins\importexport\native\filter\NativeXmlArticleFilter;
use APP\submission\Submission;
use DOMDocument;
use DOMElement;
use Illuminate\Support\Facades\DB;
use PKP\db\DAORegistry;
use PKP\note\Note;
use PKP\query\Query;
use PKP\query\QueryParticipant;
use PKP\stageAssignment\StageAssignment;
use PKP\submission\reviewAssignment\ReviewAssignment;
use PKP\submission\reviewRound\ReviewRound;
use PKP\userGroup\UserGroup;
use PKP\workflow\WorkflowStageDAO;

class NativeXmlExtendedArticleFilter extends NativeXmlArticleFilter
{
    use FullJournalFilterTrait;

    /**
     * Files whose source_submission_file_id could not be resolved at import time.
     * Key = old submission_file id from XML, value = old source submission_file id.
     *
     * @var array<string,string>
     */
    private array $pendingSourceSubmissionFileIds = [];

    private ?DOMElement $eventLogNode = null;

    /** @var ?DOMElement the submission_file_dates element of the article being imported */
    private ?DOMElement $submissionFileDatesNode = null;
    private ?DOMElement $emailLogNode = null;

    public function getClassName(): string
    {
        return static::class;
    }

    /**
     * @copydoc NativeXmlSubmissionFilter::handleElement()
     */
    public function handleElement($node)
    {
        $deployment = $this->getFullJournalDeployment();
        $this->eventLogNode = $this->emailLogNode = $this->submissionFileDatesNode = null;
        $this->pendingSourceSubmissionFileIds = [];

        $oldSubmissionId = null;
        foreach ($this->childElements($node, 'id') as $idNode) {
            if ($idNode->getAttribute('type') === 'internal') {
                $oldSubmissionId = trim($idNode->textContent);
            }
        }

        $submission = parent::handleElement($node);
        if (!$submission instanceof Submission) {
            return $submission;
        }

        if ($oldSubmissionId !== null && $oldSubmissionId !== '') {
            $deployment->setSubmissionDBId($oldSubmissionId, (int) $submission->getId());
        }
        $deployment->incrementCounter('submissions');
        $imported = $deployment->getCounters()['submissions'] ?? 0;
        if ($imported % 25 === 0) {
            echo '  ' . $imported . ' submissions...' . PHP_EOL;
        }
        $this->restoreSubmissionDates($node, $submission);
        $this->resolvePendingSourceSubmissionFileIds();
        $this->restoreSubmissionFileDates();

        // The activity log is restored last, when all IDs are known (the entries
        // generated by the import are dropped even when the source had no entries)
        if (!$deployment->hasImportOption('no-activity-log')) {
            $this->importActivityLog($submission);
        }
        $this->eventLogNode = $this->emailLogNode = null;

        return $submission;
    }

    /**
     * @copydoc NativeXmlSubmissionFilter::handleChildElement()
     */
    public function handleChildElement($node, $submission)
    {
        switch ($node->tagName) {
            case 'publication_categories':
                $this->parsePublicationCategories($node, $submission);
                return;
            case 'reviewer_suggestions':
                $this->parseReviewerSuggestions($node, $submission);
                return;
            case 'submission_file_dates':
                $this->submissionFileDatesNode = $node; // applied when all files are imported
                return;
            case 'stage_assignments':
                $this->parseStageAssignments($node, $submission);
                return;
            case 'stage':
                $this->parseStage($node, $submission);
                return;
            case 'event_log':
                $this->eventLogNode = $node;
                return;
            case 'email_log':
                $this->emailLogNode = $node;
                return;
            case 'submission_file':
                // The native filter stores source_submission_file_id verbatim; it must be mapped.
                $this->parseSubmissionFile($node);
                return;
        }
        parent::handleChildElement($node, $submission);
    }

    //
    // Stage assignments
    //
    public function parseStageAssignments(DOMElement $node, Submission $submission): void
    {
        $deployment = $this->getFullJournalDeployment();
        $context = $deployment->getContext();
        $userGroups = UserGroup::withContextIds([(int) $context->getId()])->get();

        foreach ($this->childElements($node, 'stage_assignment') as $assignmentNode) {
            $user = $this->getUserByEmail($assignmentNode->getAttribute('user_email'));
            if (!$user) {
                $this->warnUserNotFound($submission, $assignmentNode->getAttribute('user_email'));
                continue;
            }

            $userGroupRef = $assignmentNode->getAttribute('user_group_ref');
            $userGroup = null;
            foreach ($userGroups as $candidate) {
                if (in_array($userGroupRef, (array) $candidate->name, true)) {
                    $userGroup = $candidate;
                    break;
                }
            }
            if (!$userGroup) {
                $deployment->addWarning(Application::ASSOC_TYPE_SUBMISSION, $submission->getId(), __('plugins.importexport.common.error.unknownUserGroup', [
                    'authorName' => $user->getFullName(),
                    'userGroupName' => $userGroupRef,
                ]));
                continue;
            }

            $exists = StageAssignment::withSubmissionIds([(int) $submission->getId()])
                ->withUserId((int) $user->getId())
                ->withUserGroupId((int) $userGroup->id)
                ->exists();
            if ($exists) {
                continue;
            }

            StageAssignment::create([
                'submissionId' => (int) $submission->getId(),
                'userGroupId' => (int) $userGroup->id,
                'userId' => (int) $user->getId(),
                'recommendOnly' => (bool) (int) $assignmentNode->getAttribute('recommend_only'),
                'canChangeMetadata' => (bool) (int) $assignmentNode->getAttribute('can_change_metadata'),
                'dateAssigned' => $this->parseDateTime($assignmentNode->getAttribute('date_assigned')) ?? date('Y-m-d H:i:s'),
            ]);
            $deployment->incrementCounter('stage assignments');
        }
    }

    //
    // Categories of the publications
    //
    public function parsePublicationCategories(DOMElement $node, Submission $submission): void
    {
        $deployment = $this->getFullJournalDeployment();
        foreach ($this->childElements($node, 'publication_category') as $categoryNode) {
            $publicationId = $deployment->getMappedId('publication', $categoryNode->getAttribute('publication_id'));
            $categoryId = $deployment->getMappedId('category', $categoryNode->getAttribute('category_id'));
            if (!$publicationId || !$categoryId) {
                continue;
            }
            $exists = DB::table('publication_categories')
                ->where('publication_id', $publicationId)
                ->where('category_id', $categoryId)
                ->exists();
            if (!$exists) {
                DB::table('publication_categories')->insert(['publication_id' => $publicationId, 'category_id' => $categoryId]);
                $deployment->incrementCounter('publication categories');
            }
        }
    }

    //
    // Reviewers suggested by the authors
    //
    public function parseReviewerSuggestions(DOMElement $node, Submission $submission): void
    {
        $deployment = $this->getFullJournalDeployment();
        if (!DB::getSchemaBuilder()->hasTable('reviewer_suggestions')) {
            return;
        }
        foreach ($this->childElements($node, 'reviewer_suggestion') as $suggestionNode) {
            $suggestingUser = $this->getUserByEmail($suggestionNode->getAttribute('suggesting_user_email'));
            $approver = $this->getUserByEmail($suggestionNode->getAttribute('approver_email'));
            $reviewer = $this->getUserByEmail($suggestionNode->getAttribute('reviewer_email'));
            $suggestionId = DB::table('reviewer_suggestions')->insertGetId([
                'suggesting_user_id' => $suggestingUser ? (int) $suggestingUser->getId() : null,
                'submission_id' => (int) $submission->getId(),
                'email' => $suggestionNode->getAttribute('email'),
                'orcid_id' => $suggestionNode->hasAttribute('orcid_id') ? $suggestionNode->getAttribute('orcid_id') : null,
                'approved_at' => $this->parseDateTime($suggestionNode->getAttribute('approved_at')),
                'approver_id' => $approver ? (int) $approver->getId() : null,
                'reviewer_id' => $reviewer ? (int) $reviewer->getId() : null,
                'created_at' => $this->parseDateTime($suggestionNode->getAttribute('created_at')),
                'updated_at' => $this->parseDateTime($suggestionNode->getAttribute('updated_at')),
            ], 'reviewer_suggestion_id');
            $settingRows = $this->readSettingRows($suggestionNode, 'reviewer_suggestion_id', $suggestionId);
            if (!empty($settingRows)) {
                DB::table('reviewer_suggestion_settings')->insert($settingRows);
            }
            $deployment->incrementCounter('reviewer suggestions');
        }
    }

    //
    // Workflow stages
    //
    public function parseStage(DOMElement $node, Submission $submission): void
    {
        $stageId = WorkflowStageDAO::getIdFromPath($node->getAttribute('path'));
        if (!$stageId) {
            $this->getDeployment()->addWarning(Application::ASSOC_TYPE_SUBMISSION, $submission->getId(), __('plugins.importexport.common.error.unknownElement', ['param' => 'stage ' . $node->getAttribute('path')]));
            return;
        }

        foreach ($this->childElements($node) as $childNode) {
            switch ($childNode->tagName) {
                case 'review_round':
                    $this->parseReviewRound($childNode, $submission, $stageId);
                    break;
                case 'decision':
                    $this->parseDecision($childNode, $submission, $stageId);
                    break;
                case 'queries':
                    foreach ($this->childElements($childNode, 'query') as $queryNode) {
                        $this->parseQuery($queryNode, $submission, $stageId);
                    }
                    break;
            }
        }
    }

    public function parseReviewRound(DOMElement $node, Submission $submission, int $stageId): ?ReviewRound
    {
        $deployment = $this->getFullJournalDeployment();
        $reviewRoundDao = DAORegistry::getDAO('ReviewRoundDAO'); /** @var \PKP\submission\reviewRound\ReviewRoundDAO $reviewRoundDao */

        $round = (int) $node->getAttribute('round');
        $status = (int) $node->getAttribute('status');

        // build() returns an existing round (the native import creates round 1 of
        // the current review stage) or inserts a new one
        $reviewRound = $reviewRoundDao->build((int) $submission->getId(), $stageId, $round, $status);
        if (!$reviewRound) {
            return null;
        }
        if ((int) $reviewRound->getStatus() !== $status) {
            $reviewRound->setStatus($status);
            $reviewRoundDao->updateObject($reviewRound);
        }
        if ($node->hasAttribute('id')) {
            $deployment->setReviewRoundDBId($node->getAttribute('id'), (int) $reviewRound->getId());
        }
        $deployment->setReviewRound($reviewRound);
        $deployment->incrementCounter('review rounds');

        foreach ($this->childElements($node) as $childNode) {
            switch ($childNode->tagName) {
                case 'workflow_file':
                    $this->parseWorkflowFile($childNode);
                    break;
                case 'review_assignment':
                    $this->parseReviewAssignment($childNode, $submission, $reviewRound);
                    break;
                case 'decision':
                    $this->parseDecision($childNode, $submission, $stageId, $reviewRound);
                    break;
            }
        }

        $deployment->setReviewRound(null);
        return $reviewRound;
    }

    public function parseDecision(DOMElement $node, Submission $submission, int $stageId, ?ReviewRound $reviewRound = null): ?int
    {
        $deployment = $this->getFullJournalDeployment();

        $editor = $this->getUserByEmail($node->getAttribute('editor_email'));
        if (!$editor) {
            $this->warnUserNotFound($submission, $node->getAttribute('editor_email'));
            return null;
        }

        $decision = Repo::decision()->newDataObject();
        $decision->setData('submissionId', (int) $submission->getId());
        $decision->setData('stageId', $stageId);
        $decision->setData('editorId', (int) $editor->getId());
        $decision->setData('decision', (int) $node->getAttribute('decision'));
        $decision->setData('dateDecided', $this->parseDateTime($node->getAttribute('date_decided')) ?? date('Y-m-d H:i:s'));

        if ($reviewRound) {
            $decision->setData('reviewRoundId', (int) $reviewRound->getId());
            $decision->setData('round', (int) $reviewRound->getRound());
        } elseif ($node->getAttribute('round') !== '') {
            $decision->setData('round', (int) $node->getAttribute('round'));
        }

        // Insert directly: Repo::decision()->add() would run the decision
        // actions (notifications, e-mails, status changes) again.
        $decisionId = Repo::decision()->dao->insert($decision);
        $deployment->incrementCounter('editor decisions');
        return $decisionId;
    }

    //
    // Review assignments
    //
    public function parseReviewAssignment(DOMElement $node, Submission $submission, ReviewRound $reviewRound): ?ReviewAssignment
    {
        $deployment = $this->getFullJournalDeployment();

        $reviewer = $this->getUserByEmail($node->getAttribute('reviewer_email'));
        if (!$reviewer) {
            $this->warnUserNotFound($submission, $node->getAttribute('reviewer_email'));
            return null;
        }

        $reviewAssignment = Repo::reviewAssignment()->newDataObject();
        $reviewAssignment->setData('submissionId', (int) $submission->getId());
        $reviewAssignment->setData('reviewerId', (int) $reviewer->getId());
        $reviewAssignment->setData('reviewRoundId', (int) $reviewRound->getId());
        $reviewAssignment->setData('stageId', (int) $reviewRound->getStageId());
        $reviewAssignment->setData('round', (int) $reviewRound->getRound());
        $reviewAssignment->setData('reviewMethod', (int) $node->getAttribute('method'));
        $reviewAssignment->setData('step', (int) $node->getAttribute('step'));
        $reviewAssignment->setData('declined', (bool) (int) $node->getAttribute('declined'));
        $reviewAssignment->setData('cancelled', (bool) (int) $node->getAttribute('cancelled'));
        $reviewAssignment->setData('reminderWasAutomatic', (int) $node->getAttribute('reminder_was_automatic'));
        $reviewAssignment->setData('considered', (int) $node->getAttribute('considered'));
        $reviewAssignment->setData('requestResent', (bool) (int) $node->getAttribute('request_resent'));

        foreach ([
            'date_assigned' => 'dateAssigned',
            'date_notified' => 'dateNotified',
            'date_confirmed' => 'dateConfirmed',
            'date_completed' => 'dateCompleted',
            'date_acknowledged' => 'dateAcknowledged',
            'date_due' => 'dateDue',
            'date_response_due' => 'dateResponseDue',
            'last_modified' => 'lastModified',
            'date_cancelled' => 'dateCancelled',
            'date_rated' => 'dateRated',
            'date_reminded' => 'dateReminded',
            'date_considered' => 'dateConsidered',
        ] as $attribute => $prop) {
            $value = $this->parseDateTime($node->getAttribute($attribute));
            if ($value !== null) {
                $reviewAssignment->setData($prop, $value);
            }
        }
        if (!$reviewAssignment->getData('dateAssigned')) {
            $reviewAssignment->setData('dateAssigned', date('Y-m-d H:i:s'));
        }
        if (!$reviewAssignment->getData('lastModified')) {
            $reviewAssignment->setData('lastModified', $reviewAssignment->getData('dateAssigned'));
        }

        if (($quality = $node->getAttribute('quality')) !== '') {
            $reviewAssignment->setData('quality', (int) $quality);
        }
        if (($recommendation = $node->getAttribute('recommendation')) !== '') {
            $reviewAssignment->setData('recommendation', (int) $recommendation);
        }
        if (($competingInterests = $node->getAttribute('competing_interests')) !== '') {
            $reviewAssignment->setData('competingInterests', $competingInterests);
        }
        if (($oldReviewFormId = $node->getAttribute('review_form_id')) !== '') {
            $reviewFormId = $deployment->getReviewFormDBId($oldReviewFormId);
            if ($reviewFormId) {
                $reviewAssignment->setData('reviewFormId', $reviewFormId);
            } else {
                $deployment->addWarning(Application::ASSOC_TYPE_SUBMISSION, $submission->getId(), __('plugins.importexport.fullJournal.warning.reviewFormNotFound', ['id' => $oldReviewFormId]));
            }
        }

        // Insert directly: Repo::reviewAssignment()->add() recomputes the review
        // round status, which is restored from the export.
        $reviewAssignmentId = Repo::reviewAssignment()->dao->insert($reviewAssignment);
        $reviewAssignment = Repo::reviewAssignment()->get($reviewAssignmentId);
        if ($node->hasAttribute('id')) {
            $deployment->setReviewAssignmentDBId($node->getAttribute('id'), $reviewAssignmentId);
        }
        $deployment->setReviewAssignment($reviewAssignment);
        $deployment->incrementCounter('review assignments');

        foreach ($this->childElements($node, 'setting') as $settingNode) {
            $name = $settingNode->getAttribute('name');
            if ($name === '') {
                continue;
            }
            DB::table('review_assignment_settings')->updateOrInsert(
                [
                    'review_id' => $reviewAssignmentId,
                    'locale' => $settingNode->getAttribute('locale') ?: '',
                    'setting_name' => $name,
                ],
                ['setting_value' => $settingNode->textContent]
            );
        }

        foreach ($this->childElements($node) as $childNode) {
            switch ($childNode->tagName) {
                case 'workflow_file':
                    $this->parseWorkflowFile($childNode);
                    break;
                case 'review_files':
                    $reviewFilesDao = DAORegistry::getDAO('ReviewFilesDAO'); /** @var \PKP\submission\ReviewFilesDAO $reviewFilesDao */
                    foreach (explode(':', $childNode->textContent) as $oldFileId) {
                        $newFileId = $deployment->getSubmissionFileDBId(trim($oldFileId));
                        if ($newFileId && !$reviewFilesDao->check($reviewAssignmentId, $newFileId)) {
                            $reviewFilesDao->grant($reviewAssignmentId, $newFileId);
                        }
                    }
                    break;
                case 'response':
                    $this->parseResponse($childNode, $reviewAssignment);
                    break;
                case 'submission_comment':
                    $this->parseSubmissionComment($childNode, $submission, $reviewAssignment);
                    break;
            }
        }

        $deployment->setReviewAssignment(null);
        return $reviewAssignment;
    }

    public function parseResponse(DOMElement $node, ReviewAssignment $reviewAssignment): void
    {
        $deployment = $this->getFullJournalDeployment();

        $reviewFormElementId = $deployment->getReviewFormElementDBId($node->getAttribute('form_element_id'));
        if (!$reviewFormElementId) {
            $deployment->addWarning(Application::ASSOC_TYPE_SUBMISSION, $reviewAssignment->getSubmissionId(), __('plugins.importexport.fullJournal.warning.reviewFormElementNotFound', ['id' => $node->getAttribute('form_element_id')]));
            return;
        }

        $reviewFormResponseDao = DAORegistry::getDAO('ReviewFormResponseDAO'); /** @var \PKP\reviewForm\ReviewFormResponseDAO $reviewFormResponseDao */
        $response = $reviewFormResponseDao->newDataObject();
        $response->setReviewId((int) $reviewAssignment->getId());
        $response->setReviewFormElementId($reviewFormElementId);
        $type = $node->getAttribute('type') ?: 'string';
        $response->setResponseType($type);
        if ($type === 'object') {
            $decoded = json_decode($node->textContent, true);
            $response->setValue(is_array($decoded) ? $decoded : []);
        } elseif ($type === 'int') {
            $response->setValue((int) $node->textContent);
        } else {
            $response->setValue($node->textContent);
        }
        $reviewFormResponseDao->insertObject($response);
    }

    public function parseSubmissionComment(DOMElement $node, Submission $submission, ReviewAssignment $reviewAssignment): void
    {
        $deployment = $this->getFullJournalDeployment();

        $author = $this->getUserByEmail($node->getAttribute('author'));
        if (!$author) {
            $this->warnUserNotFound($submission, $node->getAttribute('author'));
            return;
        }

        $submissionCommentDao = DAORegistry::getDAO('SubmissionCommentDAO'); /** @var \PKP\submission\SubmissionCommentDAO $submissionCommentDao */
        $comment = $submissionCommentDao->newDataObject();
        $comment->setCommentType((int) $node->getAttribute('comment_type'));
        $comment->setRoleId((int) $node->getAttribute('role'));
        $comment->setSubmissionId((int) $submission->getId());
        $comment->setAssocId((int) $reviewAssignment->getId());
        $comment->setAuthorId((int) $author->getId());
        $comment->setDatePosted($this->parseDateTime($node->getAttribute('date_posted')) ?? date('Y-m-d H:i:s'));
        $comment->setDateModified($this->parseDateTime($node->getAttribute('date_modified')));
        $comment->setViewable((bool) (int) $node->getAttribute('viewable'));

        $titleNode = $this->firstChildElement($node, 'title');
        $commentsNode = $this->firstChildElement($node, 'comments');
        $comment->setCommentTitle($titleNode ? $titleNode->textContent : '');
        $comment->setComments($commentsNode ? $commentsNode->textContent : '');

        $submissionCommentDao->insertObject($comment);
        $deployment->incrementCounter('reviewer comments');
    }

    //
    // Discussions
    //
    public function parseQuery(DOMElement $node, Submission $submission, int $stageId): ?int
    {
        $deployment = $this->getFullJournalDeployment();

        $datePosted = $this->parseDateTime($node->getAttribute('date_posted')) ?? date('Y-m-d H:i:s');
        $dateModified = $this->parseDateTime($node->getAttribute('date_modified')) ?? $datePosted;

        $query = Query::create([
            'assocType' => Application::ASSOC_TYPE_SUBMISSION,
            'assocId' => (int) $submission->getId(),
            'stageId' => $stageId,
            'seq' => (float) $node->getAttribute('seq'),
            'closed' => (bool) (int) $node->getAttribute('closed'),
            'datePosted' => $datePosted,
            'dateModified' => $dateModified,
        ]);
        $queryId = (int) $query->id;
        $deployment->incrementCounter('discussions');

        $participantsNode = $this->firstChildElement($node, 'participants');
        if ($participantsNode) {
            $participantUserIds = [];
            foreach ($this->childElements($participantsNode, 'participant') as $participantNode) {
                $participant = $this->getUserByEmail($participantNode->textContent);
                if ($participant) {
                    $participantUserIds[(int) $participant->getId()] = true;
                } else {
                    $this->warnUserNotFound($submission, trim($participantNode->textContent));
                }
            }
            if (!empty($participantUserIds)) {
                QueryParticipant::insert(array_map(
                    fn ($userId) => ['query_id' => $queryId, 'user_id' => $userId],
                    array_keys($participantUserIds)
                ));
            }
        }

        $repliesNode = $this->firstChildElement($node, 'replies');
        if ($repliesNode) {
            foreach ($this->childElements($repliesNode, 'note') as $noteNode) {
                $this->parseNote($noteNode, $submission, $queryId);
            }
        }

        return $queryId;
    }

    public function parseNote(DOMElement $node, Submission $submission, int $queryId): void
    {
        $deployment = $this->getFullJournalDeployment();

        $noteUser = $this->getUserByEmail($node->getAttribute('user_email'));
        if (!$noteUser) {
            // notes.user_id is mandatory: fall back to the importing user
            $this->warnUserNotFound($submission, $node->getAttribute('user_email'));
            $noteUser = $deployment->getUser();
        }

        $dateCreated = $this->parseDateTime($node->getAttribute('date_created')) ?? date('Y-m-d H:i:s');
        $dateModified = $this->parseDateTime($node->getAttribute('date_modified')) ?? $dateCreated;
        $titleNode = $this->firstChildElement($node, 'title');
        $contentsNode = $this->firstChildElement($node, 'contents');

        $note = Note::create([
            'assocType' => Application::ASSOC_TYPE_QUERY,
            'assocId' => $queryId,
            'userId' => (int) $noteUser->getId(),
            'dateCreated' => $dateCreated,
            'dateModified' => $dateModified,
            'title' => $titleNode ? mb_substr($titleNode->textContent, 0, 255) : '',
            'contents' => $contentsNode ? $contentsNode->textContent : '',
        ]);
        $deployment->incrementCounter('discussion notes');

        $deployment->setNote($note);
        foreach ($this->childElements($node, 'workflow_file') as $fileNode) {
            $this->parseWorkflowFile($fileNode);
        }
        $deployment->setNote(null);
    }

    //
    // Files
    //
    public function parseWorkflowFile(DOMElement $node): void
    {
        $this->importNodeWith('native-xml=>workflow-file', $node);
    }

    /**
     * Import a native <submission_file> node. The native filter expects
     * source_submission_file_id to be a real database ID; in the transfer it is
     * the ID of the old installation, so it is mapped (or resolved later when
     * the referenced file is imported after this one).
     */
    public function parseSubmissionFile(DOMElement $node): void
    {
        $deployment = $this->getFullJournalDeployment();

        $oldSubmissionFileId = trim((string) $node->getAttribute('id'));
        $oldSourceSubmissionFileId = trim((string) $node->getAttribute('source_submission_file_id'));

        $submissionFileDoc = new DOMDocument('1.0', 'utf-8');
        $submissionFileNode = $submissionFileDoc->importNode($node, true);
        $submissionFileDoc->appendChild($submissionFileNode);

        // The uploader is referenced by username, which may differ on this site
        if (($uploader = $submissionFileNode->getAttribute('uploader')) !== '') {
            $mappedUsername = $deployment->getMappedUsername($uploader);
            if ($mappedUsername !== null) {
                $submissionFileNode->setAttribute('uploader', $mappedUsername);
            } elseif (!Repo::user()->getByUsername($uploader, true)) {
                $submissionFileNode->removeAttribute('uploader'); // falls back to the importing user
            }
        }

        if ($oldSourceSubmissionFileId !== '') {
            $mappedSourceSubmissionFileId = $deployment->getSubmissionFileDBId($oldSourceSubmissionFileId);
            if ($mappedSourceSubmissionFileId) {
                $submissionFileNode->setAttribute('source_submission_file_id', (string) $mappedSourceSubmissionFileId);
            } else {
                $submissionFileNode->removeAttribute('source_submission_file_id');
                if ($oldSubmissionFileId !== '') {
                    $this->pendingSourceSubmissionFileIds[$oldSubmissionFileId] = $oldSourceSubmissionFileId;
                }
            }
        }

        $importFilter = $this->getSubFilter('native-xml=>SubmissionFile');
        $result = $importFilter->execute($submissionFileDoc, true);
        if (empty($result)) {
            $deployment->addError(Application::ASSOC_TYPE_SUBMISSION, $deployment->getSubmission()?->getId(), __('plugins.importexport.common.error.submissionChildFailed', ['child' => 'submission_file']));
        }

        $this->resolvePendingSourceSubmissionFileIds();
    }

    private function resolvePendingSourceSubmissionFileIds(): void
    {
        if (empty($this->pendingSourceSubmissionFileIds)) {
            return;
        }
        $deployment = $this->getFullJournalDeployment();

        foreach ($this->pendingSourceSubmissionFileIds as $oldSubmissionFileId => $oldSourceSubmissionFileId) {
            $newSubmissionFileId = $deployment->getSubmissionFileDBId($oldSubmissionFileId);
            $newSourceSubmissionFileId = $deployment->getSubmissionFileDBId($oldSourceSubmissionFileId);
            if (!$newSubmissionFileId || !$newSourceSubmissionFileId) {
                continue;
            }
            DB::table('submission_files')
                ->where('submission_file_id', $newSubmissionFileId)
                ->update(['source_submission_file_id' => $newSourceSubmissionFileId]);
            unset($this->pendingSourceSubmissionFileIds[$oldSubmissionFileId]);
        }
    }

    /**
     * The native import stamps created_at/updated_at of the submission files with
     * the import time; restore the timestamps of the source installation.
     */
    protected function restoreSubmissionFileDates(): void
    {
        if (!$this->submissionFileDatesNode) {
            return;
        }
        $deployment = $this->getFullJournalDeployment();
        foreach ($this->childElements($this->submissionFileDatesNode, 'file_dates') as $node) {
            $submissionFileId = $deployment->getSubmissionFileDBId($node->getAttribute('id'));
            if (!$submissionFileId) {
                continue;
            }
            $columns = [];
            foreach (['created_at', 'updated_at'] as $column) {
                $value = $this->parseDateTime($node->getAttribute($column));
                if ($value !== null) {
                    $columns[$column] = $value;
                }
            }
            if (!empty($columns)) {
                DB::table('submission_files')->where('submission_file_id', $submissionFileId)->update($columns);
            }
        }
        $this->submissionFileDatesNode = null;
    }

    /**
     * The native import stamps the modification/activity dates with the import
     * time; restore the dates of the source installation.
     */
    protected function restoreSubmissionDates(DOMElement $node, Submission $submission): void
    {
        $columns = [];
        foreach (['datetime_submitted' => 'date_submitted', 'last_modified' => 'last_modified', 'date_last_activity' => 'date_last_activity'] as $attribute => $column) {
            $value = $this->parseDateTime($node->getAttribute($attribute));
            if ($value !== null) {
                $columns[$column] = $value;
            }
        }
        if (!empty($columns)) {
            DB::table('submissions')->where('submission_id', (int) $submission->getId())->update($columns);
        }
    }

    //
    // Activity log
    //
    protected function importActivityLog(Submission $submission): void
    {
        $deployment = $this->getFullJournalDeployment();
        $submissionId = (int) $submission->getId();

        $submissionFileIds = Repo::submissionFile()
            ->getCollector()
            ->filterBySubmissionIds([$submissionId])
            ->includeDependentFiles()
            ->getIds()
            ->all();

        // Replace the entries generated by the import with the original log
        ActivityLog::deleteGeneratedEventLog($submissionId, $submissionFileIds);
        if ($this->eventLogNode) {
            $count = ActivityLog::importEventLog($this->eventLogNode, $deployment, $submissionId);
            $deployment->incrementCounter('event log entries', $count);
        }
        if ($this->emailLogNode) {
            $count = ActivityLog::importEmailLog($this->emailLogNode, $deployment, $submissionId);
            $deployment->incrementCounter('email log entries', $count);
        }
    }

    /**
     * Get the import filter for a given element (publications are imported with
     * the extended publication filter which records the galley IDs).
     */
    public function getImportFilter($elementName)
    {
        if ($elementName === 'publication') {
            return $this->getSubFilter('native-xml=>extended-publication');
        }
        return parent::getImportFilter($elementName);
    }

    private function warnUserNotFound(Submission $submission, string $email): void
    {
        $this->getDeployment()->addWarning(
            Application::ASSOC_TYPE_SUBMISSION,
            $submission->getId(),
            __('plugins.importexport.fullJournal.error.userNotFound', ['email' => $email])
        );
    }
}
